name: test-event
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: install  node js
        uses:  actions/setup-node@v3
        with:
          node-version: 18
      - name: npm install
        run: npm ci
      - name: Run Tests
        run: npm test



